Unified `PlotAccessor` for DataFrame and Series (#1662)
Aims to fix #1661
New `PlotAccessor` works the same way as the old.

Examples:
```python
import pandas as pd
import databricks.koalas as ks
import matplotlib.pyplot as plt
kf =  ks.DataFrame([[1, 2, 3, 4], [5, 6, 7, 8]], columns=["A", "B", "C", "D"])
```
```python
# dataframe like
print(kf.plot)
kf.plot(kind="line")
kf.plot(kind="line", backend="plotly", width=400, height=400).show()
```
`<databricks.koalas.plot.PlotAccessor object at 0x7f32d669b590>`
![image](https://user-images.githubusercontent.com/23381512/87826163-030c2a80-c896-11ea-85bd-2e6104b7bfc7.png)
![image](https://user-images.githubusercontent.com/23381512/87826204-13bca080-c896-11ea-87e7-13d4838936fb.png)

```python
# series like
print(kf.A.plot)
kf.A.plot(kind="line");
kf.A.plot(kind="line", backend="plotly", width=400, height=400).show()
```
`<databricks.koalas.plot.PlotAccessor object at 0x7f32cdffd750>`
![image](https://user-images.githubusercontent.com/23381512/87826324-51b9c480-c896-11ea-8c0e-b6d301f96f75.png)
![image](https://user-images.githubusercontent.com/23381512/87826358-60a07700-c896-11ea-9921-a7536cc939ca.png)

### Error are handled, same as before
```python
kf.plot(kind="pie", legend=False)
kf.plot(kind="pie",  backend="plotly", width=400, height=400).show()
```
![image](https://user-images.githubusercontent.com/23381512/87826465-8f1e5200-c896-11ea-9bb4-3ee8d38fb092.png)
```bash
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
<ipython-input-13-9597ff26ce78> in <module>
      1 kf.plot(kind="pie", legend=False)
----> 2 kf.plot(kind="pie",  backend="plotly", width=400, height=400).show()

~/work/koalas/databricks/koalas/plot.py in __call__(self, kind, backend, **kwargs)
   1322 
   1323         if plot_backend.__name__ != "databricks.koalas.plot":
-> 1324             return plot_backend.plot(plot_data, kind=kind, **kwds)
   1325 
   1326         if kind not in self._all_kinds:

~/anaconda3/lib/python3.7/site-packages/plotly/__init__.py in plot(data_frame, kind, **kwargs)
    101         return histogram(data_frame, **new_kwargs)
    102     raise NotImplementedError(
--> 103         "kind='%s' not yet supported for plotting.backend='plotly'" % kind
    104     )
    105 

NotImplementedError: kind='pie' not yet supported for plotting.backend='plotly'
```
And finally
```python
# exists for dataframe like
kf.plot(kind="scatter", x='A', y='B')
# does not exist for series like
kf.A.plot(kind="scatter")
```
![image](https://user-images.githubusercontent.com/23381512/87826571-c55bd180-c896-11ea-80dc-e914135d2771.png)
```bash
---------------------------------------------------------------------------
PandasNotImplementedError                 Traceback (most recent call last)
<ipython-input-6-674f15f3badc> in <module>
----> 1 kf.A.new_plot(kind="scatter")

~/work/koalas/databricks/koalas/new_plot.py in __call__(self, kind, backend, **kwargs)
    157         if isinstance(self.data, Series):
    158             if kind not in self._series_kinds:
--> 159                 return  unsupported_function(class_name="pd.Series", method_name=kind)()
    160             return plot_series(data=self.data, kind=kind, **kwds)
    161         elif isinstance(self.data, DataFrame):

~/work/koalas/databricks/koalas/missing/__init__.py in unsupported_function(*args, **kwargs)
     21     def unsupported_function(*args, **kwargs):
     22         raise PandasNotImplementedError(
---> 23             class_name=class_name, method_name=method_name, reason=reason
     24         )
     25 

PandasNotImplementedError: The method `pd.Series.scatter()` is not implemented yet.
```