Add a config to perform natural ordering when head. (#1231)
Koalas doesn't guarantee the row ordering, so `head` could return some rows from distributed partitions and the result is not deterministic, which might confuse users. (See #411, #1064, or #1219)

```py
>>> import databricks.koalas as ks
>>> spark = ks.utils.default_session({'spark.master': 'local-cluster[4, 2, 1024]'})
>>> spark.conf.set('spark.sql.execution.arrow.enabled', True)
>>> kdf = ks.DataFrame({'a': range(10)})
>>> pdf = kdf.to_pandas().head(3)
```

```py
>>> for _ in range(100):
...     assert kdf.head(3).to_pandas().equals(pdf), 'NOT equals.'
... else:
...     print('equals.')
...
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
AssertionError: NOT equals.
```

If `compute.ordered_head` is set to True, Koalas performs natural ordering beforehand, but it will cause a performance overhead.

```py
>>> ks.options.compute.ordered_head = True
>>>
>>> for _ in range(100):
...     assert kdf.head(3).to_pandas().equals(pdf), 'NOT equals.'
... else:
...     print('equals.')
...
equals.
```

I don't think we should enable it by default due to the overhead, but it will help users debug.