Fix Series.clip not to create a new DataFrame. (#1525)
Currently `Series.clip` creates a new DataFrame, so assigning back to the anchor DataFrame can't be executed without the option "compute.ops_on_diff_frames":

```py
>>> kdf = ks.DataFrame({"a": [1, 2, 6, 4, 4, 6, 4, 3, 7]})
>>> kdf['clip'] = kdf.a.clip(3, 6)
Traceback (most recent call last):
...
ValueError: Cannot combine the series or dataframe because it comes from a different dataframe. In order to allow this operation, enable 'compute.ops_on_diff_frames' option.
```