[FIX] _builtin_table import in groupby apply (changed in pandas>=1.3.0) (#2184)
I have recently had an issue while upgrading pandas to the latest version in my Databricks environment :

`AttributeError: type object 'SelectionMixin' has no attribute '_builtin_table'`


Pandas has recently refactored the way we import the _builtin_table and is now part of the `pandas.core.common` module instead of being an attribute of the `pandas.core.base.SelectionMixin` class.

PR that was merged in the 1.3.0 : https://github.com/pandas-dev/pandas/pull/40857

This suggestion should solve the issue !