Throw a better exception in DataFrame.sort_values when multi-index column is used (#1238)
Previously, it threw the exception as below:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/.../koalas/databricks/koalas/frame.py", line 5398, in sort_values
    by = [self[colname]._scol for colname in by]
  File "/.../koalas/databricks/koalas/frame.py", line 5398, in <listcomp>
    by = [self[colname]._scol for colname in by]
  File "/.../koalas/databricks/koalas/frame.py", line 8334, in __getattr__
    "'%s' object has no attribute '%s'" % (self.__class__.__name__, key))
AttributeError: 'DataFrame' object has no attribute '_scol'
```

Can be tested as below:

```python
import pandas as pd
import databricks.koalas as ks

mi = pd.MultiIndex.from_tuples([('a', 'b')])
kdf = ks.range(10)
kdf.columns = mi
kdf.sort_values("a")
```